version: '3.8'
services:
  forum-ui:
    build:
      context: .
      target: install
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
  forum-ui-storybook:
    build:
      context: .
      target: install
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 6006:6006      
    volumes:
      - ./src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run storybook
